### ISSUE TITLE
colab example?

### ISSUE THREAD

**Issue by molo32** [mindslab-ai/faceshifter#2]
You can provide one for colab , I would appreciate it.

**Comment by usingcolor** [comment]
Hi. Which part do you want for colab? Training or inference?
I think it will be very hard to train this model on colab's device.
I can make some colab examples for inference, if there are same demands like you.

**Comment by molo32** [comment]
I don't mean to train, rather to test the quality of face swap.

**Comment by usingcolor** [comment]
I added colab example in [this](https://github.com/mindslab-ai/faceshifter/commit/68773d5cdb7b7562a93dd99c63ce9017b7ef58e8) commit
